export default function Terms() {
  return (
    <div style={{ minHeight: '100vh', background: '#0a0a0a', color: '#f0ede6', fontFamily: 'sans-serif' }}>
      <div style={{ maxWidth: '720px', margin: '0 auto', padding: '4rem 1.5rem' }}>
        <a href="/" style={{ color: '#e8ff47', textDecoration: 'none', fontSize: '14px', fontFamily: 'monospace' }}>← Back to MotoFlip</a>
        <h1 style={{ fontSize: '2rem', fontWeight: '700', fontFamily: 'Georgia, serif', margin: '2rem 0 1rem' }}>Terms of Service</h1>
        <p style={{ color: '#666', fontSize: '14px', marginBottom: '2rem' }}>Last updated: May 2026</p>

        {[
          {
            title: '1. Service description',
            body: 'MotoFlip provides AI-powered analysis of motorcycle listings to help users evaluate potential resale opportunities. Our analysis is for informational purposes only and does not constitute financial advice.'
          },
          {
            title: '2. No guarantee of accuracy',
            body: 'MotoFlip\'s flip scores, profit estimates, and market valuations are generated by AI and may not reflect actual market conditions in your area. We make no guarantees about the accuracy of any analysis. Always do your own research before making any purchase.'
          },
          {
            title: '3. User responsibility',
            body: 'You are solely responsible for any purchasing decisions you make. MotoFlip is not liable for any financial losses resulting from acting on our analysis. Used vehicle prices vary significantly by region, condition, and market timing.'
          },
          {
            title: '4. Subscription and payments',
            body: 'Pro subscriptions are billed monthly. You can cancel at any time and will retain access until the end of your billing period. We do not offer refunds for partial months.'
          },
          {
            title: '5. Acceptable use',
            body: 'You may not use MotoFlip for any illegal purpose or to violate any laws. You may not attempt to reverse engineer, scrape, or abuse our API. We reserve the right to terminate accounts that violate these terms.'
          },
          {
            title: '6. Intellectual property',
            body: 'MotoFlip and all associated content, branding, and code are owned by MotoFlip. You may not reproduce or distribute our service without permission.'
          },
          {
            title: '7. Changes to terms',
            body: 'We may update these terms at any time. Continued use of MotoFlip after changes constitutes acceptance of the new terms.'
          },
          {
            title: '8. Contact',
            body: 'Questions about these terms? Email us at support@motofliip.com'
          }
        ].map(({ title, body }) => (
          <div key={title} style={{ marginBottom: '2rem' }}>
            <h2 style={{ fontSize: '16px', fontWeight: '600', marginBottom: '8px', color: '#f0ede6' }}>{title}</h2>
            <p style={{ fontSize: '14px', color: '#888', lineHeight: '1.75' }}>{body}</p>
          </div>
        ))}

        <div style={{ borderTop: '1px solid #1a1a1a', paddingTop: '2rem', marginTop: '2rem' }}>
          <a href="/privacy" style={{ color: '#e8ff47', textDecoration: 'none', fontSize: '14px' }}>Privacy Policy →</a>
        </div>
      </div>
    </div>
  );
}
